apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudforecast-agent.fullname" . }}-config
  labels:
    {{- include "cloudforecast-agent.labels" . | nindent 4 }}
data:

  {{ if .Values.barometerAgent.prometheusUrlOverride }}
  CLOUDFORECAST_PROMETHEUS_HTTP_API_URL: '{{ .Values.barometerAgent.prometheusUrlOverride }}'
  {{ else if .Values.prometheus.enabled }}
  {{/* Issues with  */}}
  CLOUDFORECAST_PROMETHEUS_HTTP_API_URL: 'http://barometer-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local'
  {{ else }}
    {{- fail "if not using the chart-native Prometheus, a Prometheus URL must be provided" -}}
  {{ end }}

  CLOUDFORECAST_BAROMETER_CLUSTER_UUID: '{{ required "A cluster UUID is required to identify the monitored Kubernetes cluster" .Values.barometerAgent.clusterUuid }}'
