apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudforecast-agent.fullname" . }}
  labels:
    {{- include "cloudforecast-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudforecast-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cloudforecast-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudforecast-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ if .Values.barometerAgent.apiKey }}
            - name: BAROMETER_API_KEY
              value: {{ .Values.barometerAgent.apiKey | quote }}
            {{ end }}
            {{ if .Values.barometerAgent.apiKeySecret.secretName }}
            - name: BAROMETER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.barometerAgent.apiKeySecret.secretName | quote }}
                  key: {{ .Values.barometerAgent.apiKeySecret.key | quote }}
                  optional: false
            {{ end}}
          envFrom:
            - configMapRef:
                name: {{ include "cloudforecast-agent.fullname" . }}-config
                optional: false
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
